use v6;

package Neo4j:ver<0.0.1> {

  our enum ErrorCode <
    SUCCESS CONNECT-FAIL

    HTTP-SUCCESS HTTP-INFORMATIONAL HTTP-REDIRECTION
    HTTP-ERROR HTTP-CLIENT-ERROR HTTP-SERVER-ERROR

    NEO-ERROR NEO-NOAUTHSUP NEO-USRPWINV
  >;

}
